### ISSUE TITLE
how to use in application factory?

### ISSUE THREAD

**Issue by ethe** [techniq/flask-wdb#1]
i do it like this in __init__.py

``` python
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from config import config
from flask_wtf.csrf import CsrfProtect
from flask.ext.mongoengine import MongoEngine
from flask_wdb import Wdb


bootstrap = Bootstrap()
moment = Moment()
db = MongoEngine()
csrf = CsrfProtect()
wdb = Wdb()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    wdb.init_app(app)
    csrf = CsrfProtect(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app
```

but there's an error:

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/home/go/brand_new/app/__init__.py", line 27, in create_app
    wdb.init_app(app)
  File "/home/go/flasky/flasky/local/lib/python2.7/site-packages/flask_wdb.py", line 18, in init_app
    app.wsgi_app = WdbMiddleware(app.wsgi_app, start_disabled, theme)
TypeError: __init__() takes at most 3 arguments (4 given)
```

**Comment by ethe** [comment]
fixed this issue.
